before_script:
- docker info
- docker login -u grzlucki -p bla1bla2

build:
  stage: build
  script:
  - docker build -t api rest_api/
  - docker tag api grzlucki/api
  - docker push grzlucki/api

  - docker build -t scraper scraper/
  - docker tag scraper grzlucki/scraper
  - docker push grzlucki/scraper
