version: "2"
services:
  scraper:
    build: ./scraper
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:5432 scrapy crawl blog

  api:
    build: ./rest_api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - scraper
    entrypoint: dockerize -wait tcp://db:5432 python3 manage.py runserver 0.0.0.0:8080

  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bla1bla2
      - POSTGRES_DB=scrape
